kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: keep
spec:
  repo: https://github.com/sbulage/test-fleet
  branch: main
  paths:
  - nginx-helm
  targetNamespace: keep-resources
  keepResources: true
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester
