kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: test-helm-ghcr
  namespace: fleet-default
spec:
  repo: https://github.com/sbulage/test-fleet
  branch: main
  helmSecretName: ghcr-creds
  paths:
  - helm-http-docker
